### PR TITLE
#2-Collaboration-Improvements

### PR DESCRIPTION
**Pull request by BrianThomasRoss**
### Changes / Updates

- Adds `.gitattributes` to normalize line endings (pulls OS style line endings, pushes Unix style line endings)
- Add `Pipfile.lock` to `.gitignore` to avoid issues with collaboration across different OS's (lock files point to OS specific distributions)

### CODE REVIEW

**Comment by rrherr** [comment]
> Adds .gitattributes to normalize line endings (pulls OS style line endings, pushes Unix style line endings)

I like this, thanks!

> Add Pipfile.lock to .gitignore to avoid issues with collaboration across different OS's (lock files point to OS specific distributions)

But if you add Pipfile.lock to .gitignore then you don't get a deterministic build when you deploy, which is the point of using Pipenv, right?

**Comment by BrianThomasRoss** [comment]
Normally in production you would include the lock file for ensuring reproducible builds, however I would argue that for the sake of collaboration here this would fall under the scope of those instances where one would want to ignore the lock file.

>This depends on your dependencies. Using a lockfile from a different OS is fine if all your packages are modern and well-behaved (either platform-agnostic or have good cross-platform support). Otherwise Pipenv can do things wrong, like installing dependencies that don’t work, or not installing all needed dependencies.

_Originally posted by @uranusjr in https://github.com/pypa/pipenv/issues/598#issuecomment-361811946_

This seems to be especially problematic in DS / ML application which rely on sometimes extensive C or C++ extensions, and creators / maintainers have not taken sufficient steps to ensure the library is platform-agnostic.

I have seen a number of groups run into issues from having the lock files committed to VC, I think there are better ways to go about this as well too in a production environment, but for simplicity's sake, my recommendation to previous BW teams has been to remove the lock file and then commit an updated `.gitignore` where the lock file is no longer being tracked.

**Comment by rrherr** [comment]
Is there a way to have GitHub ignore Pipfile.lock, but Heroku *not* ignore it?

For example, what about this change?

1. Do add Pipfile.lock to .gitignore, and ...

2. Change the Heroku deploy docs to:

```
git add --all

git add --force Pipfile.lock

git commit -m "Deploy to Heroku"

git push heroku main:master
```

**Comment by BrianThomasRoss** [comment]
The work around I've found is to pin versions in a `.txt` and include a requirements directory with `prod.txt` and `dev.txt` 

Then in the top level a `requirements.txt` which points at `/requirements/prod.txt` with the following:

```
# Included because many Paas's require a requirements.txt file in the project root
# Just installs the production requirements.
-r requirements/prod.txt
```

which leads to the pinned versions for production, which is what will be picked up by Heroku.

```
# Everything needed in production

# Flask
Flask==1.1.2
Werkzeug==1.0.1
click>=7.0

# Database
Flask-SQLAlchemy==2.4.4
SQLAlchemy==1.3.18
psycopg2-binary==2.8.5

# Migrations
Flask-Migrate==2.5.3

# Forms
email-validator==1.1.1
Flask-WTF==0.14.3
WTForms==2.3.1

# Deployment
gevent==20.6.2
gunicorn>=19.9.0
supervisor==4.2.0

# Flask Static Digest
Flask-Static-Digest==0.1.3

# Auth
Flask-Login==0.5.0
Flask-Bcrypt==0.7.1

# Caching
Flask-Caching>=1.7.2

# Debug toolbar
Flask-DebugToolbar==0.11.0

# Environment variable parsing
environs==8.0.0

# Plotly Dash
dash<=1.13.4
dash-bootstrap-components<=0.10.3

# Pandas
pandas>=1.0.5
dash-table>=4.8.1
```

Similarly one can install the dev dependencies plus the entire production dependencies with a `/requirements/dev.txt` as follows

```
 # Everything the developer needs in addition to the production requirements
-r prod.txt

# Testing
pytest==5.4.3
WebTest==2.0.35
factory-boy==2.12.0
pdbpp==0.10.2

# Lint and code style
black==19.10b0
flake8==3.8.3
flake8-blind-except==0.1.1
flake8-debugger==3.2.1
flake8-docstrings==1.5.0
flake8-isort==3.0.0
isort==4.3.21
pep8-naming==0.11.1
```

The dev / production dependencies can be installed using Pipenv via

`pipenv install --dev`

This may prove a little complicated for students in U3 however, thus the recommendation to simply ignore the lock file and rely on the Pipfile for deployment, which would result in a non-deterministic build however avoid the cross OS collaboration issues many experience.

**Comment by rrherr** [comment]
Heroku wisely warns users if you deploy with just a `Pipfile` instead of `Pipfile.lock`. 

Assume that this template will use `Pipfile.lock` for deterministic builds on Heroku. Under this assumption, what strategies could you support to mitigate cross-platform collaboration issues?

**Comment by rrherr** [comment]
@BrianThomasRoss thank you for the great discussion here and on Slack!

So to recap, here's the plan:

- I'll merge your pull request
- Then add `git add --force Pipfile.lock` to the Heroku deploy docs
- Then add the docs, if you get a `Locking failed!` error when doing `pipenv install` or deploying to Heroku, then delete `Pipfile.lock` and try again
- That way deploying from `Pipfile.lock` is Plan A and deploying from just `Pipfile` is Plan B

This isn't a perfect solution, but let's try it and see!

**Pull request merged**
